# Analysis options for Health Box
# Strict linting configuration for high code quality and medical app standards

# Use very good analysis as the baseline for strict linting
include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "build/**"
    - "lib/l10n/generated/**"
  
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  plugins:
    - custom_lint

linter:
  rules:
    # Enforce consistency and readability
    prefer_single_quotes: true
    always_use_package_imports: true
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    
    # Security and privacy (critical for medical data)
    no_logic_in_create_state: true
    use_key_in_widget_constructors: true
    avoid_dynamic_calls: true
    
    # Performance optimizations
    avoid_function_literals_in_foreach_calls: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    
    # Code organization
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    directives_ordering: true
    prefer_relative_imports: false
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    
    # Documentation (critical for medical app)
    public_member_api_docs: false  # We'll enable this selectively
    package_api_docs: true
    
    # Error handling
    avoid_catches_without_on_clauses: false  # Sometimes we need broad catches
    avoid_catching_errors: true
    
    # Null safety
    avoid_null_checks_in_equality_operators: true
    prefer_if_null_operators: true
    
    # Medical data specific rules
    avoid_as: false  # Sometimes needed for database operations
    cascade_invocations: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true

# Custom rules for medical data handling
custom_lint:
  rules:
    - riverpod_final_provider: true
