# Analysis options for Health Box
# Strict linting configuration for high code quality and medical app standards

# Use very good analysis as the baseline for strict linting
# include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "build/**"
    - "lib/l10n/generated/**"
    - "specs/**"

  plugins:
    - custom_lint

# Custom rules for medical data handling
custom_lint:
  # rules:
  #   - riverpod_final_provider: true
