# Build configuration for Health Box
# Configures code generation for Drift database

targets:
  $default:
    builders:
      # Drift database code generation
      drift_dev|drift_dev:
        enabled: true
        options:
          # Generate companions for easier inserts/updates
          data_class_to_companions: true
          # Generate proper null safety code
          mutable_classes: false
        generate_for:
          include:
            - lib/data/models/**
            - lib/data/database/**