name: health_box
description: "Health Box - A mobile-first Flutter application for secure medical data management"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.8
  material_color_utilities: ^0.11.1

  # State Management
  flutter_riverpod: ^3.0.0-dev.17
  riverpod_annotation: ^3.0.0-dev.17

  # Database and Storage
  drift: ^2.28.1
  encrypted_drift:
    git:
      url: https://github.com/simolus3/drift.git
      path: extras/encryption
  path_provider: ^2.1.5
  path: ^1.9.1

  # File Operations
  file_picker: ^10.3.2
  image_picker: ^1.2.0
  image: ^4.2.0
  archive: ^4.0.7
  csv: ^6.0.0

  # Notifications and Reminders
  flutter_local_notifications: ^19.4.1
  timezone: ^0.10.1

  # PDF and QR Code Generation
  pdf: ^3.11.1
  qr_flutter: ^4.1.0

  # Google Drive Integration
  google_sign_in: ^7.1.1
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  http: ^1.2.2

  # OCR and ML
  google_ml_kit: ^0.20.0

  # Charts and Analytics
  fl_chart: ^1.1.0

  # Navigation
  go_router: ^16.2.1

  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Utilities
  uuid: ^4.5.1
  crypto: ^3.0.5
  logger: ^2.4.0
  connectivity_plus: ^7.0.0
  shared_preferences: ^2.3.2

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  # integration_test:
  #   sdk: flutter

  # Linting and Analysis
  flutter_lints: ^6.0.0
  very_good_analysis: ^10.0.0

  # Code Generation
  build_runner: ^2.7.1
  drift_dev: ^2.28.2
  riverpod_generator: ^3.0.0-dev.17
  riverpod_lint: ^3.0.0-dev.17

  # Testing
  mockito: ^5.4.4
  build_test: ^3.3.3

flutter:
  uses-material-design: true

  # Enable code generation for localization
  generate: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg