// Mocks generated by Mockito 5.4.6 from annotations
// in health_box/test/unit/services/profile_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:health_box/data/database/app_database.dart' as _i4;
import 'package:health_box/data/repositories/profile_dao.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ProfileDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileDao extends _i1.Mock implements _i2.ProfileDao {
  MockProfileDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.FamilyMemberProfile>> getAllProfiles() =>
      (super.noSuchMethod(
            Invocation.method(#getAllProfiles, []),
            returnValue: _i3.Future<List<_i4.FamilyMemberProfile>>.value(
              <_i4.FamilyMemberProfile>[],
            ),
          )
          as _i3.Future<List<_i4.FamilyMemberProfile>>);

  @override
  _i3.Future<_i4.FamilyMemberProfile?> getProfileById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProfileById, [id]),
            returnValue: _i3.Future<_i4.FamilyMemberProfile?>.value(),
          )
          as _i3.Future<_i4.FamilyMemberProfile?>);

  @override
  _i3.Future<List<_i4.FamilyMemberProfile>> getProfilesByName(
    String? searchTerm,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProfilesByName, [searchTerm]),
            returnValue: _i3.Future<List<_i4.FamilyMemberProfile>>.value(
              <_i4.FamilyMemberProfile>[],
            ),
          )
          as _i3.Future<List<_i4.FamilyMemberProfile>>);

  @override
  _i3.Future<String> createProfile(
    _i4.FamilyMemberProfilesCompanion? profile,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createProfile, [profile]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#createProfile, [profile]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<bool> updateProfile(
    String? id,
    _i4.FamilyMemberProfilesCompanion? profile,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [id, profile]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteProfile(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProfile, [id]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> permanentlyDeleteProfile(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#permanentlyDeleteProfile, [id]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<int> getActiveProfileCount() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveProfileCount, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<List<_i4.FamilyMemberProfile>> getProfilesByGender(
    String? gender,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProfilesByGender, [gender]),
            returnValue: _i3.Future<List<_i4.FamilyMemberProfile>>.value(
              <_i4.FamilyMemberProfile>[],
            ),
          )
          as _i3.Future<List<_i4.FamilyMemberProfile>>);

  @override
  _i3.Future<List<_i4.FamilyMemberProfile>> getProfilesByAgeRange(
    int? minAge,
    int? maxAge,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProfilesByAgeRange, [minAge, maxAge]),
            returnValue: _i3.Future<List<_i4.FamilyMemberProfile>>.value(
              <_i4.FamilyMemberProfile>[],
            ),
          )
          as _i3.Future<List<_i4.FamilyMemberProfile>>);

  @override
  _i3.Future<List<_i4.FamilyMemberProfile>> getRecentlyUpdatedProfiles({
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentlyUpdatedProfiles, [], {#limit: limit}),
            returnValue: _i3.Future<List<_i4.FamilyMemberProfile>>.value(
              <_i4.FamilyMemberProfile>[],
            ),
          )
          as _i3.Future<List<_i4.FamilyMemberProfile>>);

  @override
  _i3.Future<bool> profileExists(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#profileExists, [id]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<_i4.FamilyMemberProfile>> getProfilesWithEmergencyContact() =>
      (super.noSuchMethod(
            Invocation.method(#getProfilesWithEmergencyContact, []),
            returnValue: _i3.Future<List<_i4.FamilyMemberProfile>>.value(
              <_i4.FamilyMemberProfile>[],
            ),
          )
          as _i3.Future<List<_i4.FamilyMemberProfile>>);

  @override
  _i3.Future<List<_i4.FamilyMemberProfile>> getProfilesWithInsurance() =>
      (super.noSuchMethod(
            Invocation.method(#getProfilesWithInsurance, []),
            returnValue: _i3.Future<List<_i4.FamilyMemberProfile>>.value(
              <_i4.FamilyMemberProfile>[],
            ),
          )
          as _i3.Future<List<_i4.FamilyMemberProfile>>);

  @override
  _i3.Stream<List<_i4.FamilyMemberProfile>> watchAllProfiles() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllProfiles, []),
            returnValue: _i3.Stream<List<_i4.FamilyMemberProfile>>.empty(),
          )
          as _i3.Stream<List<_i4.FamilyMemberProfile>>);

  @override
  _i3.Stream<_i4.FamilyMemberProfile?> watchProfile(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchProfile, [id]),
            returnValue: _i3.Stream<_i4.FamilyMemberProfile?>.empty(),
          )
          as _i3.Stream<_i4.FamilyMemberProfile?>);
}
