// Mocks generated by Mockito 5.4.6 from annotations
// in health_box/test/widget/dashboard_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:health_box/data/database/app_database.dart' as _i5;
import 'package:health_box/features/profiles/services/profile_service.dart'
    as _i2;
import 'package:health_box/features/reminders/services/reminder_service.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProfileStatistics_0 extends _i1.SmartFake
    implements _i2.ProfileStatistics {
  _FakeProfileStatistics_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReminderStatistics_1 extends _i1.SmartFake
    implements _i3.ReminderStatistics {
  _FakeReminderStatistics_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProfileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileService extends _i1.Mock implements _i2.ProfileService {
  MockProfileService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.FamilyMemberProfile>> getAllProfiles() =>
      (super.noSuchMethod(
            Invocation.method(#getAllProfiles, []),
            returnValue: _i4.Future<List<_i5.FamilyMemberProfile>>.value(
              <_i5.FamilyMemberProfile>[],
            ),
          )
          as _i4.Future<List<_i5.FamilyMemberProfile>>);

  @override
  _i4.Future<_i5.FamilyMemberProfile?> getProfileById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProfileById, [id]),
            returnValue: _i4.Future<_i5.FamilyMemberProfile?>.value(),
          )
          as _i4.Future<_i5.FamilyMemberProfile?>);

  @override
  _i4.Future<List<_i5.FamilyMemberProfile>> searchProfiles(
    String? searchTerm,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchProfiles, [searchTerm]),
            returnValue: _i4.Future<List<_i5.FamilyMemberProfile>>.value(
              <_i5.FamilyMemberProfile>[],
            ),
          )
          as _i4.Future<List<_i5.FamilyMemberProfile>>);

  @override
  _i4.Future<String> createProfile(_i2.CreateProfileRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#createProfile, [request]),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#createProfile, [request]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<bool> updateProfile(
    String? id,
    _i2.UpdateProfileRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [id, request]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> deleteProfile(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProfile, [id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> permanentlyDeleteProfile(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#permanentlyDeleteProfile, [id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<_i5.FamilyMemberProfile>> getProfilesByGender(
    String? gender,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProfilesByGender, [gender]),
            returnValue: _i4.Future<List<_i5.FamilyMemberProfile>>.value(
              <_i5.FamilyMemberProfile>[],
            ),
          )
          as _i4.Future<List<_i5.FamilyMemberProfile>>);

  @override
  _i4.Future<List<_i5.FamilyMemberProfile>> getProfilesByAgeRange(
    int? minAge,
    int? maxAge,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProfilesByAgeRange, [minAge, maxAge]),
            returnValue: _i4.Future<List<_i5.FamilyMemberProfile>>.value(
              <_i5.FamilyMemberProfile>[],
            ),
          )
          as _i4.Future<List<_i5.FamilyMemberProfile>>);

  @override
  _i4.Future<List<_i5.FamilyMemberProfile>> getRecentlyUpdatedProfiles({
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentlyUpdatedProfiles, [], {#limit: limit}),
            returnValue: _i4.Future<List<_i5.FamilyMemberProfile>>.value(
              <_i5.FamilyMemberProfile>[],
            ),
          )
          as _i4.Future<List<_i5.FamilyMemberProfile>>);

  @override
  _i4.Future<int> getActiveProfileCount() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveProfileCount, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<_i2.ProfileStatistics> getProfileStatistics() =>
      (super.noSuchMethod(
            Invocation.method(#getProfileStatistics, []),
            returnValue: _i4.Future<_i2.ProfileStatistics>.value(
              _FakeProfileStatistics_0(
                this,
                Invocation.method(#getProfileStatistics, []),
              ),
            ),
          )
          as _i4.Future<_i2.ProfileStatistics>);

  @override
  _i4.Future<bool> profileExists(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#profileExists, [id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  int calculateAge(DateTime? dateOfBirth) =>
      (super.noSuchMethod(
            Invocation.method(#calculateAge, [dateOfBirth]),
            returnValue: 0,
          )
          as int);

  @override
  String getAgeCategory(DateTime? dateOfBirth) =>
      (super.noSuchMethod(
            Invocation.method(#getAgeCategory, [dateOfBirth]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#getAgeCategory, [dateOfBirth]),
            ),
          )
          as String);

  @override
  _i4.Stream<List<_i5.FamilyMemberProfile>> watchAllProfiles() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllProfiles, []),
            returnValue: _i4.Stream<List<_i5.FamilyMemberProfile>>.empty(),
          )
          as _i4.Stream<List<_i5.FamilyMemberProfile>>);

  @override
  _i4.Stream<_i5.FamilyMemberProfile?> watchProfile(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchProfile, [id]),
            returnValue: _i4.Stream<_i5.FamilyMemberProfile?>.empty(),
          )
          as _i4.Stream<_i5.FamilyMemberProfile?>);
}

/// A class which mocks [ReminderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockReminderService extends _i1.Mock implements _i3.ReminderService {
  MockReminderService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.Reminder>> getAllReminders() =>
      (super.noSuchMethod(
            Invocation.method(#getAllReminders, []),
            returnValue: _i4.Future<List<_i5.Reminder>>.value(<_i5.Reminder>[]),
          )
          as _i4.Future<List<_i5.Reminder>>);

  @override
  _i4.Future<List<_i5.Reminder>> getActiveReminders() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveReminders, []),
            returnValue: _i4.Future<List<_i5.Reminder>>.value(<_i5.Reminder>[]),
          )
          as _i4.Future<List<_i5.Reminder>>);

  @override
  _i4.Future<List<_i5.Reminder>> getUpcomingReminders({Duration? within}) =>
      (super.noSuchMethod(
            Invocation.method(#getUpcomingReminders, [], {#within: within}),
            returnValue: _i4.Future<List<_i5.Reminder>>.value(<_i5.Reminder>[]),
          )
          as _i4.Future<List<_i5.Reminder>>);

  @override
  _i4.Future<List<_i5.Reminder>> getOverdueReminders() =>
      (super.noSuchMethod(
            Invocation.method(#getOverdueReminders, []),
            returnValue: _i4.Future<List<_i5.Reminder>>.value(<_i5.Reminder>[]),
          )
          as _i4.Future<List<_i5.Reminder>>);

  @override
  _i4.Future<_i5.Reminder?> getReminderById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getReminderById, [id]),
            returnValue: _i4.Future<_i5.Reminder?>.value(),
          )
          as _i4.Future<_i5.Reminder?>);

  @override
  _i4.Future<String> createReminder(_i3.CreateReminderRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#createReminder, [request]),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#createReminder, [request]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<bool> updateReminder(
    String? id,
    _i3.UpdateReminderRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateReminder, [id, request]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> deleteReminder(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteReminder, [id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> markReminderSent(String? id, {DateTime? sentTime}) =>
      (super.noSuchMethod(
            Invocation.method(#markReminderSent, [id], {#sentTime: sentTime}),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> snoozeReminder(String? id, {int? customMinutes}) =>
      (super.noSuchMethod(
            Invocation.method(
              #snoozeReminder,
              [id],
              {#customMinutes: customMinutes},
            ),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> toggleReminderActive(String? id, bool? isActive) =>
      (super.noSuchMethod(
            Invocation.method(#toggleReminderActive, [id, isActive]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> rescheduleReminder(String? id, DateTime? newTime) =>
      (super.noSuchMethod(
            Invocation.method(#rescheduleReminder, [id, newTime]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<_i5.Reminder>> getMedicationReminders({
    String? medicationId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMedicationReminders, [], {
              #medicationId: medicationId,
            }),
            returnValue: _i4.Future<List<_i5.Reminder>>.value(<_i5.Reminder>[]),
          )
          as _i4.Future<List<_i5.Reminder>>);

  @override
  _i4.Future<List<_i5.Reminder>> getRemindersByFrequency(String? frequency) =>
      (super.noSuchMethod(
            Invocation.method(#getRemindersByFrequency, [frequency]),
            returnValue: _i4.Future<List<_i5.Reminder>>.value(<_i5.Reminder>[]),
          )
          as _i4.Future<List<_i5.Reminder>>);

  @override
  _i4.Future<List<_i5.Reminder>> getTodaysReminders() =>
      (super.noSuchMethod(
            Invocation.method(#getTodaysReminders, []),
            returnValue: _i4.Future<List<_i5.Reminder>>.value(<_i5.Reminder>[]),
          )
          as _i4.Future<List<_i5.Reminder>>);

  @override
  _i4.Future<List<_i5.Reminder>> searchReminders(String? searchTerm) =>
      (super.noSuchMethod(
            Invocation.method(#searchReminders, [searchTerm]),
            returnValue: _i4.Future<List<_i5.Reminder>>.value(<_i5.Reminder>[]),
          )
          as _i4.Future<List<_i5.Reminder>>);

  @override
  _i4.Future<int> getActiveReminderCount() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveReminderCount, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> getOverdueReminderCount() =>
      (super.noSuchMethod(
            Invocation.method(#getOverdueReminderCount, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<Map<String, int>> getReminderCountsByFrequency() =>
      (super.noSuchMethod(
            Invocation.method(#getReminderCountsByFrequency, []),
            returnValue: _i4.Future<Map<String, int>>.value(<String, int>{}),
          )
          as _i4.Future<Map<String, int>>);

  @override
  _i4.Future<_i3.ReminderStatistics> getReminderStatistics() =>
      (super.noSuchMethod(
            Invocation.method(#getReminderStatistics, []),
            returnValue: _i4.Future<_i3.ReminderStatistics>.value(
              _FakeReminderStatistics_1(
                this,
                Invocation.method(#getReminderStatistics, []),
              ),
            ),
          )
          as _i4.Future<_i3.ReminderStatistics>);

  @override
  _i4.Future<int> bulkDeleteReminders(List<String>? reminderIds) =>
      (super.noSuchMethod(
            Invocation.method(#bulkDeleteReminders, [reminderIds]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> bulkToggleReminders(
    List<String>? reminderIds,
    bool? isActive,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#bulkToggleReminders, [reminderIds, isActive]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> bulkSnoozeReminders(
    List<String>? reminderIds, {
    int? customMinutes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #bulkSnoozeReminders,
              [reminderIds],
              {#customMinutes: customMinutes},
            ),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Stream<List<_i5.Reminder>> watchActiveReminders() =>
      (super.noSuchMethod(
            Invocation.method(#watchActiveReminders, []),
            returnValue: _i4.Stream<List<_i5.Reminder>>.empty(),
          )
          as _i4.Stream<List<_i5.Reminder>>);

  @override
  _i4.Stream<List<_i5.Reminder>> watchUpcomingReminders({Duration? within}) =>
      (super.noSuchMethod(
            Invocation.method(#watchUpcomingReminders, [], {#within: within}),
            returnValue: _i4.Stream<List<_i5.Reminder>>.empty(),
          )
          as _i4.Stream<List<_i5.Reminder>>);

  @override
  _i4.Stream<_i5.Reminder?> watchReminder(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchReminder, [id]),
            returnValue: _i4.Stream<_i5.Reminder?>.empty(),
          )
          as _i4.Stream<_i5.Reminder?>);

  @override
  _i4.Stream<int> watchOverdueReminderCount() =>
      (super.noSuchMethod(
            Invocation.method(#watchOverdueReminderCount, []),
            returnValue: _i4.Stream<int>.empty(),
          )
          as _i4.Stream<int>);

  @override
  _i4.Future<bool> reminderExists(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#reminderExists, [id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  bool isOverdue(_i5.Reminder? reminder) =>
      (super.noSuchMethod(
            Invocation.method(#isOverdue, [reminder]),
            returnValue: false,
          )
          as bool);

  @override
  bool isUpcoming(
    _i5.Reminder? reminder, {
    Duration? within = const Duration(hours: 24),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#isUpcoming, [reminder], {#within: within}),
            returnValue: false,
          )
          as bool);

  @override
  List<String> getValidFrequencies() =>
      (super.noSuchMethod(
            Invocation.method(#getValidFrequencies, []),
            returnValue: <String>[],
          )
          as List<String>);
}
